In [4]:
#import important libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [5]:
#read csv file
df=pd.read_csv("Social_Network_Ads.xls")

In [6]:
#print df
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


# Insights:
Total columns=5

Total rows=400

Null values are not present in  the dataset.


In [9]:
#check null values are present or not
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [14]:
#find unique values of target column
df["Purchased"].unique()

array([0, 1], dtype=int64)

In [19]:
#Encoding on column Gender
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Gender"]=le.fit_transform(df["Gender"])

In [20]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [29]:
#scaling
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
for i in df.iloc[:,:-1]:
    df[i]=ss.fit_transform(df[[i]])

In [30]:
#split x and y
x=df.iloc[:,:-1]
x

User ID    Gender       Age  EstimatedSalary
0   -0.936579  1.020204 -1.781797        -1.490046
1    1.668387  1.020204 -0.253587        -1.460681
2   -0.320877 -0.980196 -1.113206        -0.785290
3   -1.233692 -0.980196 -1.017692        -0.374182
4    1.571389  1.020204 -1.781797         0.183751
..        ...       ...       ...              ...
395  0.004517 -0.980196  0.797057        -0.844019
396  0.203039  1.020204  1.274623        -1.372587
397 -0.520392 -0.980196  1.179110        -1.460681
398  0.886955  1.020204 -0.158074        -1.078938
399 -1.362310 -0.980196  1.083596        -0.990844

[400 rows x 4 columns]

In [31]:
y=df["Purchased"]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [32]:
#train_test_split
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=1,test_size=0.20)

In [34]:
#build model
from sklearn.svm import SVC
sc=SVC()
sc.fit(xtrain,ytrain)
ypred=sc.predict(xtest)

In [35]:
ypred

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [36]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [38]:
print(confusion_matrix(ytest,ypred))

[[39  9]
 [ 2 30]]


In [39]:
print(accuracy_score(ytest,ypred))

0.8625


In [40]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.95      0.81      0.88        48
           1       0.77      0.94      0.85        32

    accuracy                           0.86        80
   macro avg       0.86      0.88      0.86        80
weighted avg       0.88      0.86      0.86        80

